package transport

import (
	"encoding/base64"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"unicode/utf16"
)

// update regenerates the committed golden fixtures under testdata/ when set:
//
//	go test ./internal/transport -run 'Golden|Chunk' -update
//
// The generated bytes are then committed so CI verifies exact-byte stability.
var update = flag.Bool("update", false, "regenerate golden fixtures under testdata/")

// goldenScript / goldenEnv are the KNOWN inputs behind the committed fixtures.
// The env deliberately contains an apostrophe (O'Brien) to lock in PowerShell
// single-quote escaping ('' escapes ') and a secret-looking value to prove
// secrets are only ever carried inside the base64 blob, never in clear on the
// command line (DESIGN §8.1, §11).
const goldenScript = "Write-Output $env:GREETING\nWrite-Output 'launch'\n"

func goldenEnv() map[string]string {
	return map[string]string{
		"GREETING": "O'Brien",
		"TOKEN":    "s3cr3t-value",
	}
}

func readGolden(t *testing.T, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("read golden %s (run with -update to generate): %v", name, err)
	}
	return b
}

func writeGolden(t *testing.T, name string, data []byte) {
	t.Helper()
	if err := os.MkdirAll("testdata", 0o755); err != nil {
		t.Fatalf("mkdir testdata: %v", err)
	}
	if err := os.WriteFile(filepath.Join("testdata", name), data, 0o644); err != nil {
		t.Fatalf("write golden %s: %v", name, err)
	}
}

// Scenario: EncodedCommand exact bytes — the encoded command line for a known
// script + env{GREETING=O'Brien} must match the committed golden fixture, and
// the decoded UTF-16LE payload must show correct '' single-quote escaping with
// no secret value appearing outside the base64 blob (T3, golden).
func TestEncodedCommandGoldenBytes(t *testing.T) {
	got := EncodePS(goldenScript, goldenEnv())

	if *update {
		writeGolden(t, "encoded_command.golden", []byte(got))
	}
	want := string(readGolden(t, "encoded_command.golden"))
	if got != want {
		t.Fatalf("encoded command line mismatch\n got: %q\nwant: %q", got, want)
	}

	// Structural invariants on the exact bytes.
	const prefix = "powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -EncodedCommand "
	if !strings.HasPrefix(got, prefix) {
		t.Fatalf("missing expected flags prefix: %q", got)
	}
	b64 := strings.TrimPrefix(got, prefix)

	// Secret hygiene: the secret value must live ONLY inside the base64 blob.
	if strings.Contains(prefix, "s3cr3t-value") {
		t.Fatal("secret value leaked onto the visible command line")
	}

	// Decode base64 → UTF-16LE → runes and assert the escaped env prefix.
	raw, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		t.Fatalf("golden -EncodedCommand is not valid base64: %v", err)
	}
	if len(raw)%2 != 0 {
		t.Fatalf("UTF-16LE payload has odd byte length %d", len(raw))
	}
	u16 := make([]uint16, len(raw)/2)
	for i := range u16 {
		u16[i] = uint16(raw[i*2]) | uint16(raw[i*2+1])<<8
	}
	decoded := string(utf16.Decode(u16))

	// O'Brien must be escaped to O''Brien inside a single-quoted assignment,
	// emitted in sorted key order (GREETING before TOKEN).
	if !strings.Contains(decoded, "$env:GREETING='O''Brien'") {
		t.Fatalf("single-quote escaping wrong; decoded payload:\n%s", decoded)
	}
	if !strings.Contains(decoded, "$env:TOKEN='s3cr3t-value'") {
		t.Fatalf("token env assignment missing; decoded payload:\n%s", decoded)
	}
	gi := strings.Index(decoded, "$env:GREETING")
	ti := strings.Index(decoded, "$env:TOKEN")
	si := strings.Index(decoded, "Write-Output $env:GREETING")
	if !(gi < ti && ti < si) {
		t.Fatalf("env prefix not in sorted order before script body; decoded:\n%s", decoded)
	}
}

// chunkPlanEntry is the serialized golden view of one payload size's chunk plan.
type chunkPlanEntry struct {
	Size   int           `json:"size"`
	Count  int           `json:"count"`
	Chunks []uploadChunk `json:"chunks"`
}

// Scenario: Chunk math boundaries — payloads of 0/1/48000/48001 raw bytes must
// produce the exact chunk counts and offsets recorded in the golden fixture
// (T3, golden). 48000 = one full chunk; 48001 straddles into a 1-byte tail.
func TestUploadChunkPlanGolden(t *testing.T) {
	sizes := []int{0, 1, winrmChunkRaw, winrmChunkRaw + 1}
	plan := make([]chunkPlanEntry, 0, len(sizes))
	for _, s := range sizes {
		chunks := planUploadChunks(s)
		plan = append(plan, chunkPlanEntry{Size: s, Count: len(chunks), Chunks: chunks})
	}
	got, err := json.MarshalIndent(plan, "", "  ")
	if err != nil {
		t.Fatalf("marshal chunk plan: %v", err)
	}
	got = append(got, '\n')

	if *update {
		writeGolden(t, "chunk_plan.golden.json", got)
	}
	want := readGolden(t, "chunk_plan.golden.json")
	if string(got) != string(want) {
		t.Fatalf("chunk plan mismatch\n got:\n%s\nwant:\n%s", got, want)
	}
}

// Explicit boundary assertions independent of the golden file, so a wrong
// golden regeneration cannot silently bless broken math.
func TestUploadChunkPlanBoundaries(t *testing.T) {
	cases := []struct {
		size       int
		wantCount  int
		wantOffs   []int
		wantLens   []int
		wantFirsts []bool
	}{
		{0, 0, nil, nil, nil},
		{1, 1, []int{0}, []int{1}, []bool{true}},
		{winrmChunkRaw, 1, []int{0}, []int{winrmChunkRaw}, []bool{true}},
		{winrmChunkRaw + 1, 2, []int{0, winrmChunkRaw}, []int{winrmChunkRaw, 1}, []bool{true, false}},
	}
	for _, c := range cases {
		got := planUploadChunks(c.size)
		if len(got) != c.wantCount {
			t.Fatalf("size %d: chunk count=%d want %d", c.size, len(got), c.wantCount)
		}
		for i, ch := range got {
			if ch.Offset != c.wantOffs[i] {
				t.Fatalf("size %d chunk %d: offset=%d want %d", c.size, i, ch.Offset, c.wantOffs[i])
			}
			if ch.Len != c.wantLens[i] {
				t.Fatalf("size %d chunk %d: len=%d want %d", c.size, i, ch.Len, c.wantLens[i])
			}
			if ch.First != c.wantFirsts[i] {
				t.Fatalf("size %d chunk %d: first=%v want %v", c.size, i, ch.First, c.wantFirsts[i])
			}
		}
	}
}
